version: '3.8'
services:
  gateway:
    build: .
    image: aozaki-kuro/surgio
    container_name: surgio
    restart: always
    user: '1000:1000'
    ports:
      - 3130:3130
    volumes:
      - ./provider:/app/provider
      - ./template:/app/template
      - ./dist:/app/dist
      - ./surgio.conf.js:/app/surgio.conf.js
      - ./secret.js:/app/secret.js
